string=input("Enter elements:")
a=string.split()
print("The List is :",a)
string=input("Enter elements:")
b=string.split()
print("The List is :",b)
print("operations")
c=list(set(a)|set(b))
print("union operation  ",c)
d=list(set(a)&set(b))
print("intersection operation  ",d)
e=list(set(a)-set(b))
print("difference operation  ",e)
f=list(set(a)^set(b))
print("symmetric operation  ",f)
